import Image from 'next/image'
export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}
export default function HomePage() {
  console.log('HomePage')
  return (
    <main>
      <h1 className='text-6xl'>This is Home Page</h1>
    </main>
  )
}
