import Link from "next/link"

export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}
export default function HomePage() {

  return (
    <main>
      <h1 className='text-6xl'>This is Home Page</h1>
      <Link href="/blog" class="btn btn-primary">Blog</Link>
      <Link href="/news" class="btn btn-primary">News</Link>
      <Link href="/blog/tech-blog" class="btn btn-primary">tech blog</Link>
    </main>
  )
}
