import Sidebar from "@/components/shared/Sidebar"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function DashboardLayout({ children }) {
  return (

    <div className="flex">
      <Sidebar></Sidebar>
      <section className='min-h-[70vh]'>
        {
          children
        }
      </section>
    </div>

  )
}
